# Generated by Django 5.2.3 on 2025-06-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networklink',
            old_name='dept',
            new_name='debt',
        ),
    ]
