# Generated by Django 5.2.3 on 2025-06-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_rename_dept_networklink_debt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networklink',
            options={'verbose_name': 'Торговая сеть', 'verbose_name_plural': 'Торговые сети'},
        ),
        migrations.AlterField(
            model_name='networklink',
            name='name',
            field=models.IntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'ИП')], verbose_name='Тип организации'),
        ),
    ]
